# Generated by Django 6.0.5 on 2026-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url_link',
            field=models.CharField(blank=True, help_text='Alternative external image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_link',
            field=models.CharField(blank=True, help_text='Alternative external image URL', max_length=500, null=True),
        ),
    ]
